config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  post '/login', to: 'authentication#login', default: {:format => :json}
  post '/signup', to: 'authentication#signup', default: {:format => :json}

  namespace 'api' do
    namespace 'v1' do
      get 'users/:user_id/posts' => 'api#user_posts'
      get 'users/:user_id/posts/:post_id' => 'api#user_comments'
      post 'posts/:post_id/comment' => 'api#add_comment_to_post'
    end
  end
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  resources :users, only: [:index, :show, :new, :create, :destroy] do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # attribute :photo, default: default_image

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end

  def authenticate(password)
    valid_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class = "container">

<% @user.each do |p| %>
<div class = "user-row">
    <div class = "photo">
        <% if p.photo%>
            <%= image_tag p.photo %>
        <%end%>
    </div>
    <div class = "intro-details">
       <p class = "user-name"> <%= link_to p.name, p %> </p>
       <p class = "post-counter">
            <button> <%= link_to 'View profile', user_path(p) %></button>
            Number of posts:  <%= p.posts_counter %> 
       </p>
       
    </div>    
</div>

<%end%>
</div>

app/views/users/show.html.erb
<div class = "container">
    <div class = "user-row">
        <div class = "photo">
            <% if @user.photo%>
                <%= image_tag @user.photo %>
            <% end %>
        </div>
        <div class = "intro-details">
            <p class = "user-name"><%= @user.name %></p>
            <p class = "user-post-counter">Number of posts:<%= @user.posts_counter %></p>
        </div>
    </div>
    <div class = "bio">
        <p> Bio</p>
        <p><%= @user.bio %></p>
    </div>
    <% @user.recent_posts.each do |p| %>
        <div class = "post-row">
            <p class ="post-title"> <%= p.title%></p>
            <p class ="post-text"><%= p.text%></p>
            <p class="posts-footer">
                <button> <%= link_to 'View Post', user_post_url(@user, p) %></button>
                Comments: <%= p.comments_counter%>, Likes: <%= p.likes_counter%>
            </p>
            
        </div>
    <%end%>
    <p class="posts-link">
        <button><%= link_to 'See all posts', user_posts_path(@user), class: "btn-link" %></button>
    </p>
</div>