config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  post '/login', to: 'authentication#login', default: {:format => :json}
  post '/signup', to: 'authentication#signup', default: {:format => :json}

  namespace 'api' do
    namespace 'v1' do
      get 'users/:user_id/posts' => 'api#user_posts'
      get 'users/:user_id/posts/:post_id' => 'api#user_comments'
      post 'posts/:post_id/comment' => 'api#add_comment_to_post'
    end
  end
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  resources :users, only: [:index, :show, :new, :create, :destroy] do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  after_save :update_post_counter
  after_destroy :destroy_post_counter

  private

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def destroy_post_counter
    user.decrement!(:posts_counter)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def index
        @user = User.find(params[:id])
        @post = Post.where(author_id: @user.id).order(created_at: :desc)
    end

    def show
        @post = Post.find(params[:id])
        @comment = Comment.where(post_id: @post.id).order(created_at: :desc)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @user = User.find(params[:user_id])
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path, notice: 'Post successfully Deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class = "container">
    <div class = "user-row">
        <div class = "photo">
            <% if @user.photo%>
                <%= image_tag @user.photo %>
            <%end%>
        </div>
        <div class = "intro-details">
            <p class = "user-name"><%= @user.name %></p>
            <p class = "post-counter">Number of posts:<%= @user.posts_counter %></p>
        </div>
    </div>

    <div class = 'user-post-links'>
        <% if can? :create, @user %>
            <button><%= link_to 'Create New Post', new_user_post_path %></button>
        <%end%>
            <button><%= link_to 'Back to users', root_path %></button>

    </div>


    <% @user.posts.each do |p| %>
        <div class = "post-row">
            <p class ="post-title"> <%= link_to p.title, user_post_path(@user, p)%></p>
            <p class ="post-text"><%= p.text%></p>
            
            <div class="user-post-footer">
                <button><%= link_to 'View Post', user_post_path(@user, p)%></button>
                <% if can? :destroy, p%>
                    <%= button_to 'Delete Post', user_post_path(@user, p), method: :delete, data: { turbo: false} %>
                <%end%>
                <p>Comments: <%= p.comments_counter%>, Likes: <%= p.likes_counter%></p>
            </div>
        </div>
        <div class="comment-section">
            <% p.most_recent_comments.includes([:user]).each do |c|%>
                    <P><%= c.user.name + ": " + c.text%></P>
            <% end %>
        </div>

    <%end%>
    <div>
        <i>Previous</i>
        <i>1</i>
        <i>2</i>
        <i>3</i>
        <i>Next</i>
    </div>


</div>

app/views/posts/new.html.erb
<div class= "new-post-container">
  <%= form_with model: @post, url: user_posts_path(@user) do |form| %>
    <h4> Create your Post</h4>
    <p>
      <%= form.text_field :title, placeholder: "Enter post Title", class: "new-post-text" %>
    </p>
    <p>
      <%= form.text_area :text, placeholder: "Enter post description", class: "new-post-text" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %> 
</div>

app/views/posts/show.html.erb
<div class = "container">
    <div class = "post-container">
        <div class="post-header">
            <p>
                <%= @post.title %> by
                <%= @post.user.name%>
            </p>
            <p class = "post-text">
                <%= @post.text %>
            </p>
            <div class="ind-post-footer">
                <%= button_to 'Like', user_post_likes_path(@post.user_id, @post) %>
                <p>
                    Comments: <%= @post.comments_counter %>,Likes: <%= @post.likes_counter %>
                </p>
            </div>
        </div>


    </div>
    <%= render '/comments/new' %>
    <div class="comment-section">
        <% @post.most_recent_comments.includes([:user]).each do |c|%>
            <p><%= c.user.name %> : <%= c.text %></p>
            <% if can? :destroy, c %>
                <%= button_to "Remove", user_post_comment_path(current_user.id, @post.id, c.id), method: :delete, data: {turbo: false}%>
            <%end%>
        <%end%>
    </div>

    <div class='post-footer'>
        <button><%= link_to 'Back to posts', user_posts_path(@post.user_id) %></button> 
        <button><%= link_to 'Back to users', root_path %></button>
    </div>
    
</div>